# Generated by Django 2.0.5 on 2018-08-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='current_status',
            field=models.CharField(choices=[('student', 'Student'), ('employed', 'Employed'), ('unemployed', 'Unemployed')], default='student', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='itea_status',
            field=models.CharField(choices=[('member', 'General Member'), ('executive', 'Executive Member'), ('public', 'Public')], default='member', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
