# Generated by Django 2.0.5 on 2018-08-25 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20180824_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='finance',
            field=models.BooleanField(default=False),
        ),
    ]
