# Generated by Django 2.0.5 on 2019-03-31 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20180915_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='blood_group',
            field=models.CharField(choices=[('a_positive', 'A+'), ('b_positive', 'B+'), ('0_positive', 'O+'), ('ab_positive', 'AB+'), ('a_negative', 'A-'), ('b_negative', 'B-'), ('o_negative', 'O-'), ('ab_negative', 'AB-')], default='o_positive', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='father_mobile',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+8801'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='father_name',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='father_occupation',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='mother_mobile',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+8801'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
        migrations.AddField(
            model_name='profile',
            name='mother_name',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='mother_occupation',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='profile',
            name='nid',
            field=models.CharField(blank=True, max_length=17, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+8801'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
