# Generated by Django 2.0.5 on 2019-05-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20190331_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='joining_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
