# Generated by Django 2.0.5 on 2018-08-24 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IndividualBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('due_month', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_details', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrganizationBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capital', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('total_profit', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('total_loss', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('investment_details', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
