# Generated by Django 2.0.5 on 2018-08-24 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualbalance',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='organizationbalance',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
