# Generated by Django 2.0.5 on 2018-08-24 16:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0002_auto_20180824_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualbalance',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='organizationbalance',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
