# Generated by Django 2.0.5 on 2018-08-24 16:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0004_auto_20180824_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualbalance',
            name='publish',
        ),
        migrations.RemoveField(
            model_name='organizationbalance',
            name='publish',
        ),
        migrations.AlterField(
            model_name='individualbalance',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 24, 16, 32, 20, 347380, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organizationbalance',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 24, 16, 32, 20, 349040, tzinfo=utc)),
        ),
    ]
