# Generated by Django 2.0.5 on 2018-08-24 16:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0005_auto_20180824_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualbalance',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 24, 16, 33, 20, 671082, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organizationbalance',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 24, 16, 33, 20, 672203, tzinfo=utc)),
        ),
    ]
