# Generated by Django 2.0.5 on 2018-08-24 16:42

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0006_auto_20180824_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualbalance',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 24, 16, 42, 1, 327443, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='organizationbalance',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime(2018, 8, 24, 16, 42, 1, 329801, tzinfo=utc)),
        ),
    ]
