# Generated by Django 2.0.5 on 2018-08-25 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0009_auto_20180825_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualbalance',
            name='balance',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
    ]
