# Generated by Django 2.0.5 on 2019-05-04 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0011_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='individualbalance',
            options={'ordering': ['-updated']},
        ),
        migrations.RenameField(
            model_name='organizationbalance',
            old_name='capital',
            new_name='extra_expense',
        ),
        migrations.RenameField(
            model_name='organizationbalance',
            old_name='total_loss',
            new_name='extra_income',
        ),
        migrations.RenameField(
            model_name='organizationbalance',
            old_name='total_profit',
            new_name='invest_expense',
        ),
        migrations.AddField(
            model_name='individualbalance',
            name='additional',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='organizationbalance',
            name='invest_income',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
