# Generated by Django 2.0.5 on 2019-05-04 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0012_auto_20190504_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualbalance',
            name='payment_details',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
