# Generated by Django 2.0.5 on 2019-05-04 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0015_auto_20190504_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='individualbalance',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to=settings.AUTH_USER_MODEL),
        ),
    ]
