# Generated by Django 2.0.5 on 2019-05-07 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0016_auto_20190504_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organizationbalance',
            options={'ordering': ['-updated']},
        ),
    ]
