# Generated by Django 2.0.5 on 2019-05-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('balance', '0017_auto_20190508_0559'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('balance', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated'],
            },
        ),
    ]
