# Generated by Django 2.0.5 on 2018-09-08 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_comment_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='status',
            new_name='post_status',
        ),
        migrations.AddField(
            model_name='post',
            name='show_to',
            field=models.CharField(choices=[('public', 'Public'), ('member', 'Member'), ('executive', 'Executive')], default='member', max_length=10),
        ),
    ]
