# Generated by Django 2.0.5 on 2019-04-05 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_post_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('yarn', 'Yarn'), ('fabric', 'Fabric'), ('wet', 'Wet Processing'), ('apparel', 'Apparel'), ('printing', 'Printing'), ('merchandising', 'Merchandising'), ('notice', 'Notice'), ('others', 'Others')], default='others', max_length=20),
        ),
    ]
