# Generated by Django 2.0.5 on 2019-05-02 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='slug',
        ),
    ]
